 openapi: 3.1.0
info:
  title: Bear Drive API
  version: "1.0.0"
  description: API for accessing and managing Google Drive, Docs, and Sheets via a service account.
servers:
  - url: https://bear-drive-plugin-production.up.railway.app/api
paths:
  /list-files:
    get:
      operationId: listFiles
      summary: List files accessible to the service account
      responses:
        '200':
          description: A list of files
          content:
            application/json:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string

  /upload-file:
    post:
      operationId: uploadFile
      summary: Upload a file to Drive
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                parentId:
                  type: string
      responses:
        '200':
          description: File uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileId:
                    type: string

  /create-doc:
    post:
      operationId: createDoc
      summary: Create a new Google Doc
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        '200':
          description: Doc created
          content:
            application/json:
              schema:
                type: object
                properties:
                  docId:
                    type: string

  /create-sheet:
    post:
      operationId: createSheet
      summary: Create a new Google Sheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        '200':
          description: Sheet created
          content:
            application/json:
              schema:
                type: object
                properties:
                  sheetId:
                    type: string

components:
  schemas: {}
